services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ozon-test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozon-app
    depends_on:
      - db
      - migrations
    ports:
      - "8080:8080"
    command: ["./github.com/AmonRaKyelena/ozon-Test"]

volumes:
  db-data:
