// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentForPagination struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parentId,omitempty"`
	Text     string `json:"text"`
	PostID   int64  `json:"postId"`
	HasChild bool   `json:"hasChild"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   int64  `json:"postId"`
	ParentID *int64 `json:"parentId,omitempty"`
	Text     string `json:"text"`
}

type NewPost struct {
	Title    string `json:"title"`
	Text     string `json:"text"`
	ReadOnly bool   `json:"readOnly"`
}

type PostForPagination struct {
	ID       int64                   `json:"id"`
	Title    string                  `json:"title"`
	Text     string                  `json:"text"`
	ReadOnly bool                    `json:"readOnly"`
	Comments []*CommentForPagination `json:"comments,omitempty"`
}

type Query struct {
}
